name: questerix_domain
description: Shared domain models and validation for the Questerix platform.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.8
  freezed_annotation: ">=2.4.0 <4.0.0"
  json_annotation: ">=4.8.0 <5.0.0"
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.12.0
  lints: ^6.0.0
  test: ^1.25.6
