name: student_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.0.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  sqlite3: ^2.7.2
  sqlite3_flutter_libs: ^0.5.0
  connectivity_plus: ^7.0.0
  sentry_flutter: ^9.10.0
  uuid: ^4.3.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.0
  intl: ^0.19.0
  path_provider: ^2.1.0
  path: ^1.8.0
  shared_preferences: ^2.2.0
  questerix_domain:
    path: ../questerix_domain
  flutter_secure_storage: ^10.0.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.24.0
  json_serializable: ^6.8.0
  freezed: ^2.5.0
  riverpod_generator: ^2.6.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
